version: '3'

services:
  jupyter:
    build: ./docker_images/jupyter
    ports:
      - 8837:8888
      - 8838:8050
    environment:
      - JUPYTER_TOKEN=gl
    volumes:
      - ./:/home/jovyan/gl_greeen_patents
      - ../output:/home/jovyan/output
      - ../input:/home/jovyan/input

